apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  labels:
    app: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apisix
        image: apache/apisix:latest
        ports:
        - containerPort: 80
        - containerPort: 443
